# "$schema" = "https://starship.rs/config-schema.json"

command_timeout = 2_500
format = """
$os\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$fill\
$cmd_duration\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$time"""

scan_timeout = 10
add_newline = false
palette = "brilliant"

[palettes.brilliant]
text_light = "#E8ECf4"
text_gray = "#414141"
text_dark = "#011627"
blue = "#00C7fC"
cyan = "#1BD4CD"
gray = "#575656"
green = "#4CE685"
lavender = "#B4BEFE"
magenta = "#FC95DC"
orange = "#FF7023"
ruby = "#FF3662"
pink = "#FD7777"
pink_muted = "#CF829E"

[os]
disabled = false
style = "fg:text_light"

[os.symbols]
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
Raspbian = " "
Redhat = "󱄛 "
Ubuntu = " "
Unknown = " "
Windows = " "

[directory]
style = "fg:blue"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[character]
success_symbol = '[](blue) '
error_symbol = '[](red) '

[cmake]
style = "fg:#1E9748"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[cmd_duration]
style = "fg:cyan"
min_time = 0
format = "[  $duration ]($style)"

[docker_context]
symbol = ""
style = "fg:#06969A"
format = "[ $symbol $context ]($style)"

[elixir]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[elm]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[fill]
style = ""
symbol = " "

[git_branch]
symbol = " "
style = "fg:green"
format = "[ $symbol $branch(:$remote_branch) ]($style)"

[git_status]
style = "fg:orange"
format = "[$all_status$ahead_behind]($style)"
conflicted = ""
ahead = "󰶣 "
behind = "󰶡 "
diverged = "󰦽 "
untracked = "? "
stashed = " "
modified = "󰏭 "
staged = "󱪚 "
renamed = " "
deleted = "✘ "

[golang]
symbol = ""
style = "fg:#7FD5EA"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[gradle]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[haskell]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[java]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[julia]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[line_break]
disabled = true

[nodejs]
symbol = ""
style = "fg:#8ED072"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[nim]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[python]
symbol = ""
style = "fg:#FFDE57"
version_format = "$raw"
format = "[ $symbol $version \\(($virtualenv\\)) ]($style)"

[ruby]
symbol = ""
style = "fg:ruby"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "fg:#BEB3AB"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[scala]
symbol = ""
style = "fg:#86BBD8"
version_format = "$raw"
format = "[ $symbol $version ]($style)"

[time]
disabled = false
style = "fg:text_light"
format = "[  $time]($style)"
